// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDgbq57RX7nc3tf0Cr4HKFEDFQ38_mHxlQ',
    appId: '1:3108988604:web:c349dc920dcde9dd97d2b9',
    messagingSenderId: '3108988604',
    projectId: 'project-8472148077417859604',
    authDomain: 'project-8472148077417859604.firebaseapp.com',
    storageBucket: 'project-8472148077417859604.appspot.com',
    measurementId: 'G-YCY1Z79233',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBy1oUrDgnVobWs10EzfWd6mbJIvUySpfs',
    appId: '1:3108988604:android:d2e3408f98c2e24797d2b9',
    messagingSenderId: '3108988604',
    projectId: 'project-8472148077417859604',
    storageBucket: 'project-8472148077417859604.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC2Ufd0Z4mWyQTwvOi4uPP-1az048iWXYU',
    appId: '1:3108988604:ios:827fe3c5d9f138f597d2b9',
    messagingSenderId: '3108988604',
    projectId: 'project-8472148077417859604',
    storageBucket: 'project-8472148077417859604.appspot.com',
    iosBundleId: 'com.three.thousand.threeThousand',
  );
}
